apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: helse-arbeidsforhold-fihr
  namespace: tsm
  labels:
    team: tsm
spec:
  image: {{image}}
  port: 3000
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  filesFrom:
    - emptyDir:
        medium: Memory
      mountPath: /app/.next/cache
  resources:
    limits:
      cpu: 500m
      memory: 768Mi
    requests:
      cpu: 50m
      memory: 512Mi
  accessPolicy:
    outbound:
      rules:
        - application: helse-arbeidsforhold-api
  liveness:
    path: /api/internal/is_alive
  readiness:
    path: /api/internal/is_ready
