apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: helse-arbeidsforhold-standalone
  namespace: tsm
  labels:
    team: tsm
spec:
  image: {{image}}
  port: 3000
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  ingresses:
    - https://helse-arbeidsforhold.ekstern.dev.nav.no
  filesFrom:
    - emptyDir:
        medium: Memory
      mountPath: /app/.next/cache
  resources:
    limits:
      cpu: 500m
      memory: 768Mi
    requests:
      cpu: 50m
      memory: 512Mi
  accessPolicy:
    outbound:
      rules:
        - application: helse-arbeidsforhold-api
      external:
        - host: helseid-sts.test.nhn.no
  liveness:
    path: /api/internal/is_alive
  readiness:
    path: /api/internal/is_ready
  env:
    - name: NEXTAUTH_URL
      value: https://helse-arbeidsforhold.ekstern.dev.nav.no
  envFrom:
    - secret: helse-arbeidsforhold-standalone-helse-id
