name: Setup yarn deps
description: Checkout code, init yarn with deps

inputs:
  NPM_AUTH_TOKEN:
    required: true
    description: Github reader token

runs:
  using: composite
  steps:
    - name: Enable corepack
      shell: bash
      run: corepack enable
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'yarn'
    - shell: bash
      run: yarn
